# The parent dirs for these might need to be created in chezmoi before script
# So chezmoiexternal doesn't break symlinks when it encounters missing folders
{{ $xdgDataHome :=  env "XDG_DATA_HOME" | replace (print (env "HOME") "/") "" }}
{{ $xdgConfigHome :=  env "XDG_CONFIG_HOME" | replace (print (env "HOME") "/") "" }}
["{{ $xdgDataHome }}/bash/sensible.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/mrzool/bash-sensible/master/sensible.bash"
    refreshPeriod = "168h"

["{{ $xdgDataHome }}/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

["{{ $xdgConfigHome}}/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

["{{ $xdgDataHome }}/zsh/zcomet/bin"]
    type = "git-repo"
    url = "https://github.com/agkozak/zcomet.git"
    refreshPeriod = "168h"

["{{ $xdgDataHome }}/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

["bin/ediff.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/paulotome/emacstool/master/ediff.sh"
    refreshPeriod = "168h"
    executable = true

["bin/git-sync"]
    type = "file"
    url = "https://raw.githubusercontent.com/simonthum/git-sync/master/git-sync"
    refreshPeriod = "168h"
    executable = true

["bin/gnome-shell-extension-installer"]
    type = "file"
    url = "https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/master/gnome-shell-extension-installer"
    refreshPeriod = "168h"
    executable = true

{{ if .workstation }}
["{{ $xdgConfigHome }}/emacs"]
    type = "git-repo"
    url = "https://github.com/hlissner/doom-emacs"
    refreshPeriod = "0"  # use doom upgrade from script instead
{{ end }}
