# The parent dirs for these might need to be created in chezmoi before script
# So chezmoiexternal doesn't break symlinks when it encounters missing folders
{{ $xdgCacheHome := default ".cache" (env "XDG_CACHE_HOME" | replace (print (env "HOME") "/") "") }}
{{ $xdgConfigHome := default ".config" (env "XDG_CONFIG_HOME" | replace (print (env "HOME") "/") "") }}
{{ $xdgDataHome := default ".local/share" (env "XDG_DATA_HOME" | replace (print (env "HOME") "/") "") }}

["{{ $xdgDataHome }}/bash/sensible.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/mrzool/bash-sensible/master/sensible.bash"
    refreshPeriod = "168h"

["{{ $xdgCacheHome }}/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

["{{ $xdgConfigHome }}/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

["{{ $xdgCacheHome }}/zsh/zim/zimfw.zsh"]
    type = "file"
    url = "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
    refreshPeriod = "168h"
    executable = true

["{{ $xdgDataHome }}/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

["{{ $xdgDataHome }}/lscolors.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.sh"
    refreshPeriod = "168h"

["bin/ediff.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/paulotome/emacstool/master/ediff.sh"
    refreshPeriod = "168h"
    executable = true

["bin/git-sync"]
    type = "file"
    url = "https://raw.githubusercontent.com/simonthum/git-sync/master/git-sync"
    refreshPeriod = "168h"
    executable = true

["bin/gnome-shell-extension-installer"]
    type = "file"
    url = "https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/master/gnome-shell-extension-installer"
    refreshPeriod = "168h"
    executable = true

["{{ $xdgConfigHome }}/emacs"]
    type = "git-repo"
    url = "https://github.com/hlissner/doom-emacs"
    refreshPeriod = "0"  # use doom upgrade from script instead

["{{ $xdgDataHome }}/fonts"]
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/InconsolataGo.zip"
    type = "archive"
    refreshPeriod = "168h"

[".shortcuts/icons/emacsclient.sh.png"]
    type = "file"
    url = "https://git.savannah.gnu.org/cgit/emacs.git/plain/etc/images/icons/hicolor/128x128/apps/emacs.png"
    refreshPeriod = "0"
