[".config/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".config/zsh/.zcomet/bin"]
    type = "git-repo"
    url = "https://github.com/agkozak/zcomet.git"
    refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".config/emacs"]
    type = "git-repo"
    url = "https://github.com/plexus/chemacs2.git"
    refreshPeriod = "168h"

[".config/emacsconf/spacemacs"]
    type = "git-repo"
    url = "https://github.com/syl20bnr/spacemacs"
    refreshPeriod = "168h"

[".config/emacsconf/doom-emacs"]
    type = "git-repo"
    url = "https://github.com/hlissner/doom-emacs"
    refreshPeriod = "0"  # use doom upgrade from script instead

[".config/emacsconf/lisp"]
    type = "git-repo"
    url = "https://github.com/tetov/elisp"
    refreshPeriod = "168h"

[".local/share/gnome-shell/extensions/pixel-saver@deadalnix.me"]
    type = "archive"
    url = "https://extensions.gnome.org/extension-data/pixel-saverdeadalnix.me.v26.shell-extension.zip"
    refreshPeriod = "168h"

["bin/gnome-shell-extension-installer"]
    type = "file"
    url = "https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/master/gnome-shell-extension-installer"
    refreshPeriod = "168h"
    executable = true
