repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.7
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
      - id: mixed-line-ending
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
