repos:
  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.5.1
  #   hooks:
  #     - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
      - id: mixed-line-ending
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
exclude: "^gnome_extension_sync.json$"
