abbr --add g git
abbr --add ga 'git add'
abbr --add gb 'git branch'
abbr --add gc 'git commit'
abbr --add gca 'git commit --amend'
abbr --add gcm 'git commit -m'
abbr --add gco 'git checkout'
abbr --add gp 'git pull'
abbr --add gd 'git diff'
abbr --add gf 'git fetch'
abbr --add gp 'git push'
abbr --add gl 'git pull'
abbr --add grb 'git rebase'
abbr --add gst 'git status -sb'
abbr --add gcd 'cd (git rev-parse --show-toplevel; or echo ".")'
