#!/bin/env sh
# This hook is sourced after a new virtualenv is activated.

pip install pdbpp flake8 pytest pydocstyle black autopep8 jedi

PYTHONVER=`python -c 'import sys; print(sys.version_info[0])'`

if test PYTHONVER = "3"; then
  pip install mypy
fi

