#!/bin/zsh -eu
# Inspiration and code snippets from:
# https://gist.github.com/BGBRWR/82e66547d7013f3ae687eb792b6b7e20
# https://stackoverflow.com/a/45444758
# https://github.com/sindresorhus/pure

# Get git repo name using a function from sindresorhus/pure

# get repo name or if not inside a repo just the dir name
if [[ -n $prompt_pure_vcs_info[top] ]] ; then
  PROJ_DIR=$prompt_pure_vcs_info[top]  # from sindresorhus/pure
else
  PROJ_DIR=$(pwd)
fi

ENV_NAME=${PROJ_DIR:t}-dev

# Check if env with this name exists & and is not actived
if [[ -e $WORKON_HOME/$ENV_NAME/bin/activate \
  && ${VIRTUAL_ENV:t} != $ENV_NAME ]]
then
  workon $ENV_NAME
  export VENV_AUTOACTIVATED=true

# Check if virtual env is still active while outside of project dir
elif [[ -v VENV_AUTOACTIVATED ]] ; then
  deactivate
  unset VENV_AUTOACTIVATED
fi
